development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
  username: "ubuntu"
  password: "password"

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
  username: "ubuntu"
  password: "password"


production:
  adapter: postgresql
  encoding: unicode
  database: yelp_production
  pool: 5
  username: "ubuntu"
  password: "password"
