# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410e1665aae11bd3c713a95f1e3e42bdd3f639f9197dbb9fa15df27b139e70553468f213cc0db70bb0a01badb058ef1da60607c752b007e94f997df492428062

test:
  secret_key_base: f867d2e066cc097c6d74d0136919d694dd352784fc6990f8c909d7df6c27576518803177559a72c5ffb9dc574051b297b141e7bb156cce490f596ec00a278709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
